# Generated by Django 6.0.7 on 2026-09-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True, verbose_name='中文词')),
                ('pinyin', models.CharField(blank=True, default='', max_length=100, verbose_name='拼音')),
                ('description', models.TextField(blank=True, default='', verbose_name='手语动作说明')),
                ('video_url', models.CharField(blank=True, default='', max_length=255, verbose_name='手语动作视频 URL')),
                ('generated', models.BooleanField(default=False, verbose_name='是否已生成视频与说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '手语词',
                'verbose_name_plural': '手语词',
                'ordering': ['id'],
            },
        ),
    ]
