# Generated by Django 6.0.7 on 2026-07-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextToSignRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(verbose_name='输入文本')),
                ('matched_text', models.TextField(blank=True, default='', verbose_name='匹配到的原文')),
                ('matched_gloss', models.TextField(blank=True, default='', verbose_name='匹配到的Gloss')),
                ('video_name', models.CharField(blank=True, default='', max_length=255, verbose_name='视频文件名')),
                ('similarity', models.FloatField(default=0.0, verbose_name='相似度')),
                ('method', models.CharField(choices=[('retrieval', '向量检索'), ('deepseek', 'DeepSeek改写'), ('gloss', 'Gloss匹配')], default='retrieval', max_length=20, verbose_name='匹配方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文本转手语记录',
                'verbose_name_plural': '文本转手语记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
