# Generated by Django 6.0.7 on 2026-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255, verbose_name='视频文件名')),
                ('gloss_text', models.TextField(blank=True, default='', verbose_name='手语 Gloss 序列')),
                ('chinese_text', models.TextField(blank=True, default='', verbose_name='中文翻译结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '翻译记录',
                'verbose_name_plural': '翻译记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
