# Generated by Django 6.0.7 on 2026-09-08 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '素材文件夹',
                'verbose_name_plural': '素材文件夹',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='text', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='records.materialfolder')),
            ],
            options={
                'verbose_name': '素材',
                'verbose_name_plural': '素材',
                'ordering': ['-created_at'],
            },
        ),
    ]
